Convert the project to gradle groovy
unldenis/holoeasy pull request #51
Opened 2024-02-03 15:45 UTC by GeorgeV220

Changes may be required.

Compile command: `./gradlew clean build shadowJar`

2024-02-03 17:10 UTC, unldenis commented
But Gradle used to work, just call shadowJar. The problem is uploading it right to a repository, jitpack or mavencentral.

2024-02-03 17:12 UTC, GeorgeV220 commented
> But Gradle used to work, just call shadowJar. The problem is uploading it right to a repository, jitpack or mavencentral.

I'm trying to figure it out, that's why I have it as draft.

2024-02-03 17:13 UTC, unldenis commented
Oh ok let me know!

2024-02-03 18:21 UTC, unldenis commented
thank you very much, but I can ask you two questions:
- I think the part where you relocate the kotlin stdlib.(package kotlin.*) is missing
- can you convert it to gradle kotlin ?

2024-02-03 18:24 UTC, GeorgeV220 commented
> * I think the part where you relocate the kotlin stdlib.(package kotlin.*) is missing

![image](https://github.com/unldenis/holoeasy/assets/30936682/39a546e7-9f90-4ac0-9c2a-6097d572e3f0)
in the final jar the kotlin relocated package exists.



> * can you convert it to gradle kotlin ?

I did it in groovy in order to be easier for me (I do not use kotlin at all). But I can do it.

2024-02-03 19:14 UTC, GeorgeV220 commented
I've switched all Gradle scripts to use gradle.kts, but I'm a bit stuck with the gradle/publish.gradle file. Not sure how to convert the shadow JAR publication to Kotlin. Anyway, everything else seems to work just fine!!

2024-04-09 21:17 UTC, GeorgeV220 commented
Any reason why it should be gradle kotlin ? @unldenis

2024-04-10 04:38 UTC, huanmeng-qwq requested changes

2024-04-10 04:38 UTC, huanmeng-qwq commented on build.gradle.kts
> +    withType<ShadowJar> {
tasks.shadowJar {
// ...
}

2024-04-10 04:38 UTC, huanmeng-qwq commented on build.gradle.kts
> +    named("build") {
tasks.build {
// ...
}

2024-04-10 04:38 UTC, huanmeng-qwq commented on build.gradle.kts
> +    id("org.jetbrains.kotlin.jvm") version "1.9.22"
```suggestion
    kotlin("jvm") version "1.9.22"
```

2024-04-10 04:38 UTC, huanmeng-qwq commented on core/build.gradle.kts
> +    id("org.jetbrains.kotlin.jvm") version "1.9.22"
```suggestion
    kotlin("jvm") version "1.9.22"
```

2024-04-10 04:38 UTC, huanmeng-qwq commented on core/build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.22")
```suggestion
```
The dependency already exists by default

2024-04-10 04:38 UTC, huanmeng-qwq commented on core/build.gradle.kts
> +}
```suggestion
```
I don't think it's necessary to set the main class?

2024-04-10 04:38 UTC, huanmeng-qwq commented on core/build.gradle.kts
> +version = "3.1.1"
```suggestion
```
The submodule does not need to repeat this content as it will automatically retrieve the parent project's

2024-04-10 04:38 UTC, huanmeng-qwq commented on example/build.gradle.kts
> +version = "1.0-SNAPSHOT"
```suggestion
```

2024-10-07 22:36 UTC, unldenis commented
> Any reason why it should be gradle kotlin ? @unldenis

Sorry for the late reply, but since I didn't receive the notification and, despite having also opened the PR every now and then, I never read this message.
We can keep it in gradle groovy too.
If you want to open another one or correct this one I'll merge, I just need to be sure that there are no build or jitpack problems.

2024-11-03 16:59 UTC, GeorgeV220 commented
Check #68

2024-11-03 16:59 UTC, closed without merging